### ISSUE TITLE
Source of thr tables?

### ISSUE THREAD

**Issue by mrivas** [dpryan79/ChromosomeMappings#10]
Thanks for compiling these tables. Could you comment on their sources?

**Comment by dpryan79** [comment]
Sure, these are largely generated from files available via Genbank. There, one can find assembly reports for various builds of the different organisms. There are multiple chromosome/contig naming schemes in each, so the trick is just to determine which columns to use for which contig type in each data source. I usually just write a little python script for each organism. I can post those elsewhere later today so people can see how they work.

**Comment by dpryan79** [comment]
Here's an example script: https://gist.github.com/dpryan79/ce3d119113646bb1b7752a721fd7eb79

**Comment by mrivas** [comment]
Thanks Devon.
