### ISSUE TITLE
Some patch mappings are wrong

### ISSUE THREAD

**Issue by dpryan79** [dpryan79/ChromosomeMappings#16]
Namely, the mappings between patches in Ensembl and NCBI are wrong, since Ensembl N-pads contigs while NCBI doesn't. This should be checked and clarified in the repo.

**Comment by dpryan79** [comment]
This is now fixed. Thanks to @nsoranzo for mentioning the issue!

**Comment by nsoranzo** [comment]
Thank you @dpryan79!
