### ISSUE TITLE
License for Files

### ISSUE THREAD

**Issue by Kekananen** [dpryan79/ChromosomeMappings#30]
What is the license for this directory? Would it be possible to add the license to it? There's a tool in development in which we would like to use these files as a part of.

Thanks in advance!

**Comment by dpryan79** [comment]
@Kekananen I guess I forgot to add one, I'll add something very permissive today.

**Comment by dpryan79** [comment]
I just added an MIT license, which I figure is permissive enough.

**Comment by Kekananen** [comment]
Thanks. That's perfect.
