### ISSUE TITLE
Unrecognized VM option 'AggressiveOpts'

### ISSUE THREAD

**Issue by chiefcat** [dpryan79/ChromosomeMappings#33]
Hi Ryan,

Thanks for this handy tool!

I've tried to use it, and the following error message pops up.
Is it something to do with the settings of my computer?

Unrecognized VM option 'AggressiveOpts'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Thanks!
Chiefcat

**Comment by dpryan79** [comment]
These are chromosome name mappings, there's nothing to run here.
