### ISSUE TITLE
Let's integrate this into deeptools!

### ISSUE THREAD

**Issue by bgruening** [dpryan79/ChromosomeMappings#6]
:)

**Comment by dpryan79** [comment]
I'm happy to do so, it's just a question of how it'd be useful. I imagine that this could be the basis for a useful Galaxy tool...

**Comment by vejnar** [comment]
The simplicity of this repository is I think the main advantage of it as (i) it makes contribution easy, (ii) using it is light (small size) and (iii) and implementation detail free. IMHO, I would favour keeping it separated from any particular tool.

(Copy-pasting a git repo inside another is possible I think to integrate it into deeptools)

**Comment by bgruening** [comment]
@vejnar don't worry the idea is not to add tools to this repository, it's more like using these files from deeptools directly.
git has a concept of submodules that makes it easy to chain different repositories together without copy and paste.

**Comment by dpryan79** [comment]
See also here: https://github.com/galaxyproject/galaxy/issues/1477

**Comment by jennaj** [comment]
So we have a few issues open about this, from different angles but all is good and are now linked. 

We'll figure out the best places to incorporate (maybe a few places!). When I first ran across this last summer I was like "What a fabulous resource, let's use it _everywhere_"
