### ISSUE TITLE
Could you explain how to generate?

### ISSUE THREAD

**Issue by lmmx** [dpryan79/ChromosomeMappings#7]
Hi, thanks for sharing these tables. I'm working with Ensembl accessions and Genome Reference Consortium issue mapping, and the GenBank (nuccore) accession is the only way I can find to map the issue title to the chromosome/contig name.

This isn't as straightforward as it first looks for some patches (e.g. [issue `HG-1703`](www.ncbi.nlm.nih.gov/projects/genome/assembly/grc/human/issues/?id=HG-1703) maps to contig name `HG237_PATCH` (via GenBank ID: `KE332506.1`, matched [through your table](https://github.com/dpryan79/ChromosomeMappings/blob/master/GRCh37_ensembl2gencode.txt#L297)).

I'd really like to add these mappings to the [tables of issues](https://github.com/lmmx/grc-issues) I've made from processing the GRC XML but I can't find the source you've used.

Could you please suggest where/how I could reproduce the mappings in the Ensembl ⇒ Gencode tables?

**Comment by dpryan79** [comment]
Unfortunately there's often some manual effort in creating these mappings. For the various mappings I wrote some python scripts to compare the lengths and associated genbank IDs. I then followed that with some manual curation. The general level of annoyance in doing that is the reason that I created this repository.

**Comment by lmmx** [comment]
Ah, alright, could you give me an idea of what the Python scripts accessed for input data? I don't like the sound of manual curation, I'd expect this should be available through existing resources, surely.

**Comment by dpryan79** [comment]
Normally you can find a file on NCBI that has the scaffold IDs from the assembly. There are a couple columns in that and 99% of the time those can be used to convert names between gencode<->ensembl<->ucsc. That's currently the only primary source I've ever found.

**Comment by dpryan79** [comment]
Ah, it's `scaffold_localID2acc`, which is available under genbank on the NCBI ftp server. I always double checked things using chromosome sizes and you still have to play around with name munging, but that'll usually help.

**Comment by dpryan79** [comment]
Annoyingly, there are typically a bunch of these per release, so you have to go through all of them.

**Comment by lmmx** [comment]
Great, will give it a go. Thanks Devon
