### ISSUE TITLE
Mouse/human mappings need to be updated

### ISSUE THREAD

**Issue by dpryan79** [dpryan79/ChromosomeMappings#8]
Mouse got an update today and human a couple days ago, the "recent" patches/fixes need to get included. I should also check for updates to zebra fish and fruit fly. If someone else would like to do one of these then feel free :)
- [ ] GRCm38
- [ ] GRCh38

I should probably start doing this every six months or so.

**Comment by chambm** [comment]
Can we automate the update process, and at the same time increase the breadth of covered species by crawling the Genbank site?
